import './globals.css'
import { Inter } from 'next/font/google'
import { Raleway } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const roboto = Raleway({
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata = {
  title: 'Next.js playground',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
